object Compose {
    const val composeVersion = "1.3.0"
    const val composeCompilerVersion = "1.4.3"
    const val composeUiTooling = "1.1.1"
    private const val navigationVersion = "2.5.0"
    private const val hiltNavigationComposeVersion = "1.0.0"
    private const val activityComposeVersion = "1.4.0"
    private const val lifecycleVersion = "2.6.0"
    private const val pagingVersion = "0.13.0"
    private const val pagingIndicatorVersion = "0.13.0"
    //Material 3
    const val material3_Version = "1.0.0-alpha13"
    const val material_icons_extended_version = "1.5.1"
    const val constraintLayout_version = "1.0.1"

    const val material_icons_extended = "androidx.compose.material:material-icons-extended:$material_icons_extended_version"
    const val material_3 = "androidx.compose.material3:material3:$material3_Version"
    const val material = "androidx.compose.material:material:$composeVersion"
    const val materialIcons = "androidx.compose.material:material-icons-extended:$composeVersion"
    const val ui = "androidx.compose.ui:ui:$composeVersion"
    const val uiToolingPreview = "androidx.compose.ui:ui-tooling-preview:$composeVersion"
    const val uiTooling = "androidx.compose.ui:ui-tooling:$composeUiTooling"
    const val runtime = "androidx.compose.runtime:runtime:$composeVersion"
    const val compiler = "androidx.compose.compiler:compiler:$composeCompilerVersion"
    const val navigation = "androidx.navigation:navigation-compose:$navigationVersion"
    const val hiltNavigationCompose = "androidx.hilt:hilt-navigation-compose:$hiltNavigationComposeVersion"
    const val activityCompose = "androidx.activity:activity-compose:$activityComposeVersion"
    const val viewModelCompose = "androidx.lifecycle:lifecycle-viewmodel-compose:$lifecycleVersion"
    const val lifecycleCompose = "androidx.lifecycle:lifecycle-runtime-compose:$lifecycleVersion"
    const val pagingCompose = "com.google.accompanist:accompanist-pager:$pagingVersion"
    const val pagingIndicatorCompose = "com.google.accompanist:accompanist-pager-indicators:$pagingIndicatorVersion"
    const val constraintLayoutCompose = "androidx.constraintlayout:constraintlayout-compose:$constraintLayout_version"
}
